package com.example.pedidoservice.service;

import com.example.pedidoservice.dto.OrderDto;
import com.example.pedidoservice.dto.OrderWithUserDto;
import com.example.pedidoservice.mapper.OrderMapper;
import com.example.pedidoservice.messaging.UserResponse;
import com.example.pedidoservice.messaging.UserServiceConsumer;
import com.example.pedidoservice.messaging.UserServiceProducer;
import com.example.pedidoservice.model.Order;
import com.example.pedidoservice.model.State;
import com.example.pedidoservice.repository.OrderJpaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Order Service - Manages order operations with PostgreSQL persistence.
 *
 * Refactored to use ONLY OrderJpaRepository (PostgreSQL) instead of file-based OrderRepository.
 * All operations are now transactional and backed by PostgreSQL database.
 *
 * @author TDD Engineering Team
 * @since HU-ORD-05 REFACTOR Phase
 */
@Service
@Transactional
public class OrderService {

    @Autowired
    private OrderJpaRepository orderJpaRepository;

    @Autowired
    private OrderMapper orderMapper;


    @Autowired
    private UserServiceProducer userServiceProducer;

    @Autowired
    private UserServiceConsumer userServiceConsumer;

    private static final long USER_REQUEST_TIMEOUT = 3000; // 3 seconds timeout

    @Autowired
    public OrderService(OrderJpaRepository orderJpaRepository, OrderMapper orderMapper,
                        UserServiceProducer userServiceProducer, UserServiceConsumer userServiceConsumer) {
        this.orderJpaRepository = orderJpaRepository;
        this.orderMapper = orderMapper;
        this.userServiceProducer = userServiceProducer;
        this.userServiceConsumer = userServiceConsumer;
    }

    public OrderDto createOrder(OrderDto orderDto) {
        /**
         * HU-ORD-05: Create a new order with validation and PostgreSQL persistence.
         *
         * Validations (FR-ORD-05-02):
         * - name: required, not null, not empty, not blank
         * - description: required, not null
         * - idUser: required, must be > 0
         *
         * Automatic assignments (FR-ORD-05-03):
         * - id: auto-generated by PostgreSQL
         * - state: PROCESSING by default
         * - active: true by default
         *
         * @param orderDto Order data to create
         * @return Created order with assigned ID
         * @throws IllegalArgumentException if validation fails
         */

        // Validar campos requeridos
        validateOrderDto(orderDto);

        // Mapear a entidad
        Order order = orderMapper.toEntity(orderDto);

        // Asignar valores por defecto (FR-ORD-05-03)
        order.setState(State.PROCESSING);
        order.setActive(true);

        // Guardar en PostgreSQL (FR-ORD-05-01)
        // El ID es autogenerado por PostgreSQL (@GeneratedValue)
        Order savedOrder = orderJpaRepository.save(order);

        return orderMapper.toDto(savedOrder);
    }

    /**
     * Validates required fields for order creation (HU-ORD-05).
     *
     * @param orderDto Order data to validate
     * @throws IllegalArgumentException if any validation fails
     */
    private void validateOrderDto(OrderDto orderDto) {
        if (orderDto == null) {
            throw new IllegalArgumentException("El pedido no puede ser null");
        }

        // Validar 'name': no null, no vacío, no blank
        if (orderDto.getName() == null) {
            throw new IllegalArgumentException("El campo 'name' es requerido");
        }
        if (orderDto.getName().trim().isEmpty()) {
            throw new IllegalArgumentException("El campo 'name' no puede estar vacío");
        }

        // Validar 'description': no null
        if (orderDto.getDescription() == null) {
            throw new IllegalArgumentException("El campo 'description' es requerido");
        }

        // Validar 'idUser': debe ser > 0 (también verifica null)
        if (orderDto.getIdUser() == null || orderDto.getIdUser() <= 0) {
            throw new IllegalArgumentException("El campo 'idUser' debe ser un valor positivo válido (mayor que cero)");
        }
    }

    /**
     * Soft-delete an order by ID (sets active=false).
     *
     * @param id Order ID to delete
     * @throws IllegalArgumentException if order not found
     */
    public void deleteOrder(Integer id) {
        Order order = orderJpaRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Pedido con ID " + id + " no encontrado"));
        order.setActive(false);
        orderJpaRepository.save(order);
    }

    /**
     * Change the state of an order.
     *
     * @param id Order ID
     * @param newState New state to set
     * @return Updated order DTO
     * @throws IllegalArgumentException if order not found
     */
    public OrderDto changeStateOrder(Integer id, State newState) {
        Order order = orderJpaRepository.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("Pedido con ID " + id + " no encontrado"));
        order.setState(newState);
        Order savedOrder = orderJpaRepository.save(order);
        return orderMapper.toDto(savedOrder);
    }

    /**
     * List all orders for a specific user.
     *
     * @param idUser User ID
     * @return List of orders for the user
     */
    public List<OrderDto> listOrdersByIdUser(Integer idUser) {
        return orderJpaRepository.findByIdUser(idUser).stream()
                .map(orderMapper::toDto)
                .collect(Collectors.toList());
    }


    public OrderWithUserDto getOrderWithUserInfo(Integer orderId) {
        /**
         * Retrieve an order and attempt to append user information obtained
         * via the asynchronous user service. The method sends a user info
         * request over RabbitMQ and blocks up to `USER_REQUEST_TIMEOUT` ms
         * waiting for the response.
         *
         * If the user service cannot be reached or a response isn't received
         * within the timeout the returned `OrderWithUserDto` will include a
         * null user payload and the order data is still returned.
         */
        // Get the order first
        OrderDto orderDto = showOrderById(orderId);
        if (orderDto == null) {
            return null;
        }

        // Request user information via RabbitMQ using the orderId's userId
        Integer idUser = orderDto.getIdUser();
        UserResponse userResponse = null;
        try {
            userServiceProducer.requestUserInfo(idUser);
            // Wait for user response
            userResponse = userServiceConsumer.getUserResponse(idUser, USER_REQUEST_TIMEOUT);
        } catch (Exception ex) {
            // Log and continue — return order with null user if messaging fails
            System.err.println("Error requesting/receiving user info for userId=" + idUser + ": " + ex.getMessage());
        }

        // Map to OrderWithUserDto including user information
        return new OrderWithUserDto(
                orderDto.getId(),
                orderDto.getName(),
                orderDto.getDescription(),
                orderDto.getIdUser(),
                orderDto.getState(),
                orderDto.isActive(),
                userResponse
        );
    }


    /**
     * Lists all orders from the database (including inactive).
     *
     * @deprecated Use {@link #findAllActiveOrders()} instead for production use.
     * This method includes inactive (soft-deleted) orders and should only be used
     * for administrative or audit purposes.
     *
     * @return List of all orders (active and inactive)
     */
    @Deprecated
    public List<OrderDto> listAllOrders() {
        return orderJpaRepository.findAll().stream()
                .map(orderMapper::toDto)
                .collect(Collectors.toList());
    }

    /**
     * Retrieves all active orders from PostgreSQL database.
     *
     * Business Rules (HU-ORD-01):
     * - Only returns orders where active=true
     * - Returns empty list if no active orders exist
     * - Orders with active=false are excluded (soft-deleted)
     *
     * Performance:
     * - Should respond in < 200ms for up to 1000 records (NFR-ORD-01-01)
     * - Uses database-level filtering (optimized query via @Query)
     * - Connection pooling via HikariCP
     *
     * @return List of active orders as DTOs, empty list if none exist
     */
    public List<OrderDto> findAllActiveOrders() {
        return orderJpaRepository.findAllActive().stream()
                .map(orderMapper::toDto)
                .collect(Collectors.toList());
    }

    /**
     * Retrieve an order by ID.
     *
     * @param id Order ID
     * @return Order DTO or null if not found
     */
    public OrderDto showOrderById(Integer id) {
        return orderJpaRepository.findById(id)
                .map(orderMapper::toDto)
                .orElse(null);
    }
}
